### ISSUE TITLE
Configuration impossible

### ISSUE THREAD

**Issue by jpmartin71** [lfpoulain/ha-eco2mix#3]
Bonjour,
j'ai tenté d'installé l'intégration mais impossible d'accéder à la configuration des senseurs.
1 - Lorsque j'ajoute l'intégration j'ai un message "Configuration créée pour éCO2mix." 
![Capture d’écran 2024-12-12 003545](https://github.com/user-attachments/assets/eb56b488-388e-4310-b70a-f129940dacdc)
mais dans l'intégration il m'indique "Echec de la configuration" et je n'ai pas moyen (ou pas trouvé) comment la mettre à jour.
![Capture d’écran 2024-12-12 003621](https://github.com/user-attachments/assets/11f3caf4-f627-4d4c-8906-d2e5ec4df68f)

2 - lors du téléchargement sur HACS il me confirme que je télécharge la version 1.0.1 mais sur l'intégration c'est la version 1.0.0
![Capture d’écran 2024-12-12 003652](https://github.com/user-attachments/assets/b790b93e-d9b1-4103-bc62-4e0670b51cd4)
C'est pourtant bien la V1.0.1 car j'ai le correctif de pitaya
 
Auriez-vous une piste la vidéo donne envie :-) comme d'hab.

**Comment by freefloris** [comment]
Bonjour,

J'ai exactement le même problème, avec les mêmes screenshots.

J'ai tout supprimé, tout redémarré et tout réinstallé, sans succès.

Les logs ne sont pas très parlants pour moi, mais peut-être qu'ils vous seront utiles.

```
2024-12-12 00:47:33.657 ERROR (SyncWorker_2) [custom_components.eco2mix.coordinator] No valid data found in API response
2024-12-12 00:47:33.666 ERROR (MainThread) [custom_components.eco2mix.coordinator] No data received from API
2024-12-12 00:47:33.666 ERROR (MainThread) [custom_components.eco2mix.coordinator] API has been unavailable for 0 attempts (never since last success)
2024-12-12 00:47:33.667 ERROR (MainThread) [custom_components.eco2mix.coordinator] Unexpected error: No cached data available
Traceback (most recent call last):
  File "/config/custom_components/eco2mix/coordinator.py", line 48, in _async_update_data
    return await self._handle_api_failure()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eco2mix/coordinator.py", line 99, in _handle_api_failure
    raise UpdateFailed("No cached data available")
homeassistant.helpers.update_coordinator.UpdateFailed: No cached data available
2024-12-12 00:47:33.699 WARNING (MainThread) [custom_components.eco2mix.coordinator] First API failure, loading cached data
2024-12-12 00:47:33.700 ERROR (MainThread) [custom_components.eco2mix] Error fetching initial data

```
Encore merci pour votre plugin et pour l'excellente vidéo d'aujourd'hui.
Bon courage et bonne continuation !

**Comment by sebaspar** [comment]
Bonsoir, problème tout pareil,
lors de la validation de l'ajout de l’intégration -> la fenêtre "Sélectionner les capteurs souhaités" est vide.
tentative avec v1.0.0 et  v1.0.1
Bon courage et bonne nuit

**Comment by piitaya** [comment]
L’API est en maintenance chaque nuit entre minuit et 1h. Est-ce que cela marche maintenant? 🙂

**Comment by LZselo** [comment]
Bonjour.
Essai chez moi ce matin et exactement le même problème :(.

**Comment by lfpoulain** [comment]
> Problème identifié et corrigé chez moi: il faut être en version 2024.12 au minimum pour que cela fonctionne: https://www.home-assistant.io/blog/2024/12/04/release-202412/#other-noteworthy-changes

Merci pour la trouvaille, on va apporter les modifications nécessaires pour réclamer la version 2024.12

**Comment by lfpoulain** [comment]
L'intégration passe en 1.0.2, vous pouvez mettre a jour HA (2024.12 obligatoire) puis l'intégration. 
J'ai eu un bug au premier chargement, j'ai du reload mais ça marche maintenant.

**Comment by lfpoulain** [comment]
> Bonsoir, problème tout pareil, lors de la validation de l'ajout de l’intégration -> la fenêtre "Sélectionner les capteurs souhaités" est vide. tentative avec v1.0.0 et v1.0.1 Bon courage et bonne nuit

Il n'y a plus la page de sélections des capteurs c'est normal, il faut les activer après dans l'intégration

**Comment by jpmartin71** [comment]
Bonjour, 
effectivement j'ai testé entre 00h et 01h pas de bol :-)
Mise à jour en V1.0.2, ça fonctionne.
Par contre la version affichée dans le service est toujours en V1.0.0 (1.0.2 dans l'intégration).
